name: node_webkit
author: Luiz Mineo <luiz.mineo@gmail.com>
version: 0.0.7
description: node-webkit.dart is a Dart package to build node-webkit apps
homepage: https://github.com/luizmineo/node-webkit.dart
dependencies:
  browser: ">=0.10.0 <0.11.0"